/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PatentsRouteImport } from './routes/patents'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClinicalValidationRouteImport } from './routes/clinical-validation'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PatentsRoute = PatentsRouteImport.update({
  id: '/patents',
  path: '/patents',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicalValidationRoute = ClinicalValidationRouteImport.update({
  id: '/clinical-validation',
  path: '/clinical-validation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/applications': typeof ApplicationsRoute
  '/clinical-validation': typeof ClinicalValidationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/hotels': typeof HotelsRoute
  '/investors': typeof InvestorsRoute
  '/patents': typeof PatentsRoute
  '/products': typeof ProductsRoute
  '/technology': typeof TechnologyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/applications': typeof ApplicationsRoute
  '/clinical-validation': typeof ClinicalValidationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/hotels': typeof HotelsRoute
  '/investors': typeof InvestorsRoute
  '/patents': typeof PatentsRoute
  '/products': typeof ProductsRoute
  '/technology': typeof TechnologyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/applications': typeof ApplicationsRoute
  '/clinical-validation': typeof ClinicalValidationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/hotels': typeof HotelsRoute
  '/investors': typeof InvestorsRoute
  '/patents': typeof PatentsRoute
  '/products': typeof ProductsRoute
  '/technology': typeof TechnologyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/applications'
    | '/clinical-validation'
    | '/contact'
    | '/faq'
    | '/hotels'
    | '/investors'
    | '/patents'
    | '/products'
    | '/technology'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/applications'
    | '/clinical-validation'
    | '/contact'
    | '/faq'
    | '/hotels'
    | '/investors'
    | '/patents'
    | '/products'
    | '/technology'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/applications'
    | '/clinical-validation'
    | '/contact'
    | '/faq'
    | '/hotels'
    | '/investors'
    | '/patents'
    | '/products'
    | '/technology'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApplicationsRoute: typeof ApplicationsRoute
  ClinicalValidationRoute: typeof ClinicalValidationRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HotelsRoute: typeof HotelsRoute
  InvestorsRoute: typeof InvestorsRoute
  PatentsRoute: typeof PatentsRoute
  ProductsRoute: typeof ProductsRoute
  TechnologyRoute: typeof TechnologyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patents': {
      id: '/patents'
      path: '/patents'
      fullPath: '/patents'
      preLoaderRoute: typeof PatentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinical-validation': {
      id: '/clinical-validation'
      path: '/clinical-validation'
      fullPath: '/clinical-validation'
      preLoaderRoute: typeof ClinicalValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApplicationsRoute: ApplicationsRoute,
  ClinicalValidationRoute: ClinicalValidationRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HotelsRoute: HotelsRoute,
  InvestorsRoute: InvestorsRoute,
  PatentsRoute: PatentsRoute,
  ProductsRoute: ProductsRoute,
  TechnologyRoute: TechnologyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
