/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PatentsRouteImport } from './routes/patents'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as HowToUseRouteImport } from './routes/how-to-use'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClinicalValidationRouteImport } from './routes/clinical-validation'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDemoRequestsRouteImport } from './routes/admin.demo-requests'
import { Route as AdminPageRouteImport } from './routes/admin.$page'
import { Route as ApiPublicCmsImageSplatRouteImport } from './routes/api/public/cms-image.$'

const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PatentsRoute = PatentsRouteImport.update({
  id: '/patents',
  path: '/patents',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToUseRoute = HowToUseRouteImport.update({
  id: '/how-to-use',
  path: '/how-to-use',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicalValidationRoute = ClinicalValidationRouteImport.update({
  id: '/clinical-validation',
  path: '/clinical-validation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDemoRequestsRoute = AdminDemoRequestsRouteImport.update({
  id: '/demo-requests',
  path: '/demo-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPageRoute = AdminPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicCmsImageSplatRoute = ApiPublicCmsImageSplatRouteImport.update({
  id: '/api/public/cms-image/$',
  path: '/api/public/cms-image/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/clinical-validation': typeof ClinicalValidationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/hotels': typeof HotelsRoute
  '/how-to-use': typeof HowToUseRoute
  '/investors': typeof InvestorsRoute
  '/patents': typeof PatentsRoute
  '/products': typeof ProductsRoute
  '/technology': typeof TechnologyRoute
  '/admin/$page': typeof AdminPageRoute
  '/admin/demo-requests': typeof AdminDemoRequestsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/cms-image/$': typeof ApiPublicCmsImageSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/clinical-validation': typeof ClinicalValidationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/hotels': typeof HotelsRoute
  '/how-to-use': typeof HowToUseRoute
  '/investors': typeof InvestorsRoute
  '/patents': typeof PatentsRoute
  '/products': typeof ProductsRoute
  '/technology': typeof TechnologyRoute
  '/admin/$page': typeof AdminPageRoute
  '/admin/demo-requests': typeof AdminDemoRequestsRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/cms-image/$': typeof ApiPublicCmsImageSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/clinical-validation': typeof ClinicalValidationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/hotels': typeof HotelsRoute
  '/how-to-use': typeof HowToUseRoute
  '/investors': typeof InvestorsRoute
  '/patents': typeof PatentsRoute
  '/products': typeof ProductsRoute
  '/technology': typeof TechnologyRoute
  '/admin/$page': typeof AdminPageRoute
  '/admin/demo-requests': typeof AdminDemoRequestsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/cms-image/$': typeof ApiPublicCmsImageSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/applications'
    | '/auth'
    | '/clinical-validation'
    | '/contact'
    | '/faq'
    | '/hotels'
    | '/how-to-use'
    | '/investors'
    | '/patents'
    | '/products'
    | '/technology'
    | '/admin/$page'
    | '/admin/demo-requests'
    | '/admin/'
    | '/api/public/cms-image/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/applications'
    | '/auth'
    | '/clinical-validation'
    | '/contact'
    | '/faq'
    | '/hotels'
    | '/how-to-use'
    | '/investors'
    | '/patents'
    | '/products'
    | '/technology'
    | '/admin/$page'
    | '/admin/demo-requests'
    | '/admin'
    | '/api/public/cms-image/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/applications'
    | '/auth'
    | '/clinical-validation'
    | '/contact'
    | '/faq'
    | '/hotels'
    | '/how-to-use'
    | '/investors'
    | '/patents'
    | '/products'
    | '/technology'
    | '/admin/$page'
    | '/admin/demo-requests'
    | '/admin/'
    | '/api/public/cms-image/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApplicationsRoute: typeof ApplicationsRoute
  AuthRoute: typeof AuthRoute
  ClinicalValidationRoute: typeof ClinicalValidationRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HotelsRoute: typeof HotelsRoute
  HowToUseRoute: typeof HowToUseRoute
  InvestorsRoute: typeof InvestorsRoute
  PatentsRoute: typeof PatentsRoute
  ProductsRoute: typeof ProductsRoute
  TechnologyRoute: typeof TechnologyRoute
  ApiPublicCmsImageSplatRoute: typeof ApiPublicCmsImageSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patents': {
      id: '/patents'
      path: '/patents'
      fullPath: '/patents'
      preLoaderRoute: typeof PatentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-use': {
      id: '/how-to-use'
      path: '/how-to-use'
      fullPath: '/how-to-use'
      preLoaderRoute: typeof HowToUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinical-validation': {
      id: '/clinical-validation'
      path: '/clinical-validation'
      fullPath: '/clinical-validation'
      preLoaderRoute: typeof ClinicalValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/demo-requests': {
      id: '/admin/demo-requests'
      path: '/demo-requests'
      fullPath: '/admin/demo-requests'
      preLoaderRoute: typeof AdminDemoRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$page': {
      id: '/admin/$page'
      path: '/$page'
      fullPath: '/admin/$page'
      preLoaderRoute: typeof AdminPageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/cms-image/$': {
      id: '/api/public/cms-image/$'
      path: '/api/public/cms-image/$'
      fullPath: '/api/public/cms-image/$'
      preLoaderRoute: typeof ApiPublicCmsImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminPageRoute: typeof AdminPageRoute
  AdminDemoRequestsRoute: typeof AdminDemoRequestsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPageRoute: AdminPageRoute,
  AdminDemoRequestsRoute: AdminDemoRequestsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ApplicationsRoute: ApplicationsRoute,
  AuthRoute: AuthRoute,
  ClinicalValidationRoute: ClinicalValidationRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HotelsRoute: HotelsRoute,
  HowToUseRoute: HowToUseRoute,
  InvestorsRoute: InvestorsRoute,
  PatentsRoute: PatentsRoute,
  ProductsRoute: ProductsRoute,
  TechnologyRoute: TechnologyRoute,
  ApiPublicCmsImageSplatRoute: ApiPublicCmsImageSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
